import type { DashboardContract } from '../types'

export const dashboardFixture: DashboardContract = {
  contract_version: '1.0',
  generated_from: 'data/raw/incidents_synthetic.csv',
  window: {
    start: '2026-09-01T00:00:00+00:00',
    end: '2026-09-05T00:00:00+00:00',
  },
  summary: {
    incident_count: 2,
    resolved_incident_count: 1,
    open_incident_count: 1,
    downtime_minutes: 60,
    mttr_minutes: 60,
    recurrence_count: 0,
    availability_pct: 99.5,
    site_count: 2,
  },
  by_carrier: [
    {
      carrier: 'Claro',
      incident_count: 1,
      resolved_incident_count: 1,
      open_incident_count: 0,
      downtime_minutes: 60,
      mttr_minutes: 60,
      recurrence_count: 0,
      availability_pct: 99.3,
      site_count: 1,
    },
    {
      carrier: 'Vivo',
      incident_count: 1,
      resolved_incident_count: 0,
      open_incident_count: 1,
      downtime_minutes: 0,
      mttr_minutes: 0,
      recurrence_count: 0,
      availability_pct: 100,
      site_count: 1,
    },
  ],
  by_site: [
    {
      site_id: 'SITE-001',
      incident_count: 1,
      resolved_incident_count: 1,
      open_incident_count: 0,
      downtime_minutes: 60,
      mttr_minutes: 60,
      recurrence_count: 0,
      availability_pct: 99.3,
      site_count: 1,
    },
    {
      site_id: 'SITE-002',
      incident_count: 1,
      resolved_incident_count: 0,
      open_incident_count: 1,
      downtime_minutes: 0,
      mttr_minutes: 0,
      recurrence_count: 0,
      availability_pct: 100,
      site_count: 1,
    },
  ],
  by_cause: [
    {
      cause_category: 'fiber_break',
      incident_count: 1,
      resolved_incident_count: 1,
      open_incident_count: 0,
      downtime_minutes: 60,
      mttr_minutes: 60,
      recurrence_count: 0,
      availability_pct: 99.3,
      site_count: 1,
    },
    {
      cause_category: 'unknown',
      incident_count: 1,
      resolved_incident_count: 0,
      open_incident_count: 1,
      downtime_minutes: 0,
      mttr_minutes: 0,
      recurrence_count: 0,
      availability_pct: 100,
      site_count: 1,
    },
  ],
  timeline: [
    {
      opened_date: '2026-09-01',
      incident_count: 1,
      resolved_incident_count: 1,
      open_incident_count: 0,
      downtime_minutes: 60,
    },
    {
      opened_date: '2026-09-02',
      incident_count: 1,
      resolved_incident_count: 0,
      open_incident_count: 1,
      downtime_minutes: 0,
    },
  ],
  incidents: [
    {
      incident_id: 'INC-0001',
      site_id: 'SITE-001',
      carrier: 'Claro',
      opened_at: '2026-09-01T10:00:00+00:00',
      restored_at: '2026-09-01T11:00:00+00:00',
      status: 'resolved',
      cause_category: 'fiber_break',
      region: 'SE',
      link_type: 'fiber',
      source: 'synthetic',
      downtime_minutes: 60,
    },
    {
      incident_id: 'INC-0002',
      site_id: 'SITE-002',
      carrier: 'Vivo',
      opened_at: '2026-09-02T10:00:00+00:00',
      restored_at: null,
      status: 'open',
      cause_category: 'unknown',
      region: 'S',
      link_type: 'radio',
      source: 'synthetic',
      downtime_minutes: null,
    },
  ],
}
